---
version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    restart: unless-stopped
    hostname: elasticsearch
    environment:
      cluster.name: "kafka-elastic"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms16g -Xmx16g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536        
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - elasticsearch.${DOMAIN_NAME}

  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION}
    restart: unless-stopped
    hostname: kibana
    environment:
      SERVER_NAME: "kibana.${DOMAIN_NAME}"
      ELASTICSEARCH_URL: "http://elasticsearch.${DOMAIN_NAME}:9200"
    networks:
      default:
        aliases:
          - kibana.${DOMAIN_NAME}

  filebeat1:
    image: docker.elastic.co/beats/filebeat:5.6.4
    restart: unless-stopped
    hostname: filebeat1
    volumes:
      - ./../work/kafka:/opt/kafka
      - ./config/filebeat/module/kafka:/usr/share/filebeat/module/kafka
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./config/filebeat/filebeat.template.json:/usr/share/filebeat/filebeat.template.json
      - ./config/filebeat/filebeat.template-es2x.json:/usr/share/filebeat/filebeat.template-es2x.json
      - ./config/filebeat/filebeat.template-es6x.json:/usr/share/filebeat/filebeat.template-es6x.json
    networks:
      default:

  dns:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    command: -d     

volumes:
  esdata1:
    driver: local

networks:
  default:
...