module_version: 1.0

var:
  - name: kafka_home
    default: /opt/kafka*
  - name: paths
    default:
      - "{{.kafka_home}}/requestlog/request.log*"

ingest_pipeline: ingest/pipeline.json
prospector: config/log.yml
