filebeat.modules:
- module: kafka
  log:
    enabled: true
    var.kafka_home: /opt/kafka
    #var.paths:
    prospector:
    - input_type: log
      scan_frequency: 2s
      close_removed: true
      close_inactive: 1m
      ignore_older: 0
      max_bytes: 20971520
      fields:
        meta.log.source.name: kafka
        meta.log.source.id: 1
        meta.log.source.version: "0.11.0.2"
      fields_under_root: true

#name: filebeat
fields:
  meta.env.name: iac-target-elastic
  meta.log.source.hostname: "iac-target-elastic-kafka01"
fields_under_root: true

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  index: "filebeat-%{[meta.env.name]}-%{[fileset.module]}-%{[fileset.name]}-default-%{+yyyy.MM.dd}"
  indices:
    - index: "filebeat-%{[meta.env.name]}-%{[fileset.module]}-%{[fileset.name]}-large-%{+yyyy.MM.dd}"
      when.contains:
        message: "(kafka.request.logger)"
    - index: "filebeat-%{[meta.env.name]}-%{[fileset.module]}-%{[fileset.name]}-large-%{+yyyy.MM.dd}"
      when.regexp:
        message: "TRACE.*\\(kafka.server.KafkaApis\\)$"        
  template.name: "filebeat"
  template.path: "filebeat.template.json"
  template.overwrite: true
  template.versions.2x.path: "filebeat.template-es2x.json"
  template.versions.6x.path: "filebeat.template-es6x.json"
  worker: 8
  compression_level: 1
  max_retries: 10
  username: elastic
  password: changeme